name: theGrid.mattroberts.com
favicon: null
layout_spectrum: 0.7508
typography_spectrum: 0.5679363107774407
title: the Grid for Matt Roberts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.25562271382659674
  rhythmicContrast: 0.75
purpose: []
